packages:
  # 公共依赖
  - 'packages/common-tools'
  - 'packages/common-three'
  # 平台系统元素
  - 'elemental/elemental-weather'
  # 平台级功能子应用
  - 'platform/platform-auth'
  - 'platform/platform-portal'
  # 休闲放松游戏
  - 'games/games-farm'
